BaseNoiseModel:
  calibrated: false
  data_model_name: dr6v3
  dtype: f4
  fwhm_ivar: null
  kfilt_lbounds: null
  mask_est_name: dr6v3_20220316_baseline_union_mask
  mask_obs_name: dr6v3_xlink_union_mask_0.001
  mask_version: v3
  union_sources: regular_20220316

# 20220919
FDWNoiseModel:
  fwhm_fact_pt1:
  - 1350
  - 10.0
  fwhm_fact_pt2:
  - 5400
  - 16.0
  lamb: 1.6
  n: 36
  nback:
  - 0
  nforw:
  - 0
  - 6
  - 6
  - 6
  - 6
  - 12
  - 12
  - 12
  - 12
  - 24
  - 24
  p: 2
  pback:
  - 0
  pforw:
  - 0
  - 6
  - 4
  - 2
  - 2
  - 12
  - 8
  - 4
  - 2
  - 12
  - 8
  w_lmax: 10800
  w_lmax_j: 5300
  w_lmin: 10
  model_str_template: cmb_night_{arrsfreqs}_{model_name}_{config_name}_lmax{lmax}_8way_set{split_num}_noise_model
  sim_str_template: cmb_night_{arrsfreqs}_{model_name}_{config_name}_lmax{lmax}_8way_set{split_num}_noise_sim_{alm_str}{sim_num}
